---
title: "Explorative Data Analysis"
output: html_document
---

```{r setup}
library(tidyverse)
library(plyr)
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 10,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
crime_raw <- 
  read_csv("./data/cdi.csv")
```

## Data clean
```{r}
region_chr <- c("Northeast", "North Central", "South", "West")

crime_raw <- 
  crime_raw %>% 
  mutate(
    crime_per1k = crimes / pop * 10^3,
    per_area = area / pop * 10^3,
    per_doc = docs / pop * 10^3,
    per_bed = beds / pop * 10^3,
    region = region_chr[region]
    ) %>% 
  select(-c(4, 5, 8:10, 16))

crime_df <- 
  crime_raw %>% 
  arrange(desc(crime_per1k)) %>% 
  tail(-4)
```

## Distribution of target variable
```{r}
# Boxplot
crime_df %>% 
  ggplot(aes(y = crime_per1k)) + 
  geom_boxplot()

# Density
crime_df %>% 
  ggplot(aes(x = crime_per1k, alpha = .6)) + 
  geom_density(fill = "chocolate2", show.legend = FALSE) + 
  labs(
    x = "CRM_1000",
    y = "Density"
  )
```

## Check correlation between variables
```{r}
# Correlation heatmap
cor_df <- 
  crime_df %>%  
  select(-c(1:3, 11)) %>% 
  cor() %>% 
  round(3)

  ggcorrplot::ggcorrplot(
  cor_df,
  type = "lower",
  hc.order = TRUE,
  lab = TRUE,
  lab_size = 3)
```

```{r}
# Another cor map
crime_try <- 
  crime_df %>% 
  select(-c(1:3))
  
cor_data <-
  cor(cbind(crime_per1k = pull(crime_try, crime_per1k), 
  model.matrix(crime_per1k ~ ., data = crime_try)[,-1]))

# Select `poverty`, `regionNorth`, `regionSouth`, `per_doc`, `per_bed`
cor_data %>% 
  corrplot::corrplot(method = "color", addCoef.col = "black", tl.col = "black", tl.srt = 45, insig = "blank" , number.cex = 0.7, diag = FALSE, mar = c(.1,.1,.1,.1))
```


## Check marginal distributions of the above variables
```{r}
detach(package:plyr)

# Distribution of `poverty`
poverty_plt <-   
  crime_df %>% 
  ggplot(aes(y = poverty)) + 
  geom_boxplot(fill = "skyblue2") + 
  labs(y = "Poverty (%)")

# Distribution of `region`
crime_df %>% 
  group_by(region) %>% 
  summarize(count = n())

# Distribution of `pop18`
pop18_plt <- 
  crime_df %>% 
  ggplot(aes(y = pop18)) + 
  geom_boxplot(fill = "chartreuse3") + 
  labs(y = "Population aged 18-34 (%)")

# Distribution of `per_doc`
perdoc_plt <- 
  crime_df %>% 
  ggplot(aes(y = per_doc)) + 
  geom_boxplot(fill = "gold2") + 
  labs(y = "Active physicians (1k ppopulation)")

# Distribution of `per_bed`
perbed_plt <- 
  crime_df %>% 
  ggplot(aes(y = per_bed)) + 
  geom_boxplot(fill = "indianred2") + 
  labs(y = "Hospital beds (1k population)")

(poverty_plt + pop18_plt) / (perdoc_plt + perbed_plt)
```


## Export data
```{r}
# write_csv(crime_df, "./data/crime_df.csv")
```

