---
title: "Linear regression"
output: html_document
---
```{r}
library(tidyverse)
library(modelr)
library(performance)

knitr::opts_chunk$set(
  fig.width = 10,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(10)
```

```{r}
# Import data
crime_df <- 
  read_csv("./data/crime_df.csv")
```


## Distribution of target variable `crime_per1k`
```{r}
# The plot shows lambda = 1, so no transformation needed
crime_df <- 
  crime_df %>% 
  dplyr::select(-c(1:3)) 

par(mar = c(1, 1, 1, 1))

fit1 <- lm(crime_per1k ~ ., data = crime_df)
MASS::boxcox(fit1, lambda = seq(-3, 3, by = .25))
```

```{r}
# Get rid of the 316th observation based on diagnostics
crime_df = crime_df[-c(316), ]
```


## Predictors selection from EDA
`poverty`, `region`, `per_doc`, `per_bed`, `pop18`
```{r}
# Check collinearity between predictors
check_collinearity(fit1)
```

## Interactions
```{r}

```


## Fit models and diagnositics
```{r}
mod1 <- lm(crime_per1k ~ pop18 + poverty + region + per_doc + per_bed + pop18, data = crime_df)

par(mfrow = c(2, 2))
plot(mod1)

summary(mod1)

mod2 <- lm(crime_per1k ~ pop18 + poverty + region + per_doc + per_bed + pop18 + per_doc * per_bed + poverty * per_doc + poverty * per_bed, data = crime_df)
summary(mod2)

par(mfrow = c(2, 2))
plot(mod2)
```

## Model validation
```{r}
cv_df = crossv_mc(crime_df, 10)

cv_df <- 
  cv_df %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))
```

```{r}
cv_df = 
  cv_df %>% 
  mutate(
    non_interact = map(train, ~lm(crime_per1k ~ pop18 + poverty + region + per_doc + per_bed, data = .x)), 
    linear_mod  = map(train, ~lm(crime_per1k ~ pop18 + poverty + region + per_doc + per_bed + per_doc * per_bed + poverty * per_doc + poverty * per_bed, data = .x))
    ) %>% 
  mutate(
    rmse_non = map2_dbl(.x = non_interact, .y = test, ~ modelr::rmse(model = .x, data = .y)),
    rmse_linear = map2_dbl(.x = linear_mod, .y = test, ~ modelr::rmse(model = .x, data = .y)))
```

```{r}
# Plot RMSE
cv_df %>%
  dplyr::select(starts_with("rmse")) %>%
  pivot_longer(
    rmse_linear:rmse_non,
    names_to = "model",
    values_to = "rmse",
    names_prefix = "rmse"
  ) %>%
  mutate(model = fct_inorder(model)) %>%
  ggplot(aes(x = model, y = rmse, fill = model, alpha = .8)) +
  geom_violin() +
  scale_fill_manual(values = c("#ff595e","#6a4c93")) + 
  labs(y = "RMSE",
       x = "") + 
  scale_x_discrete(labels = c("Model 1","Model 2")) + 
  theme(legend.position = "none")
```

